drop table Measurement;
drop table Sensor;

CREATE TABLE sensor
(
    id   INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE measurement
(
    id                    int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    value                 DOUBLE PRECISION NOT NULL,
    raining               BOOLEAN          NOT NULL,
    date_time_measurement TIMESTAMP        NOT NULL,
    sensor_id             int references sensor ("id") ON DELETE CASCADE
);

